name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and test
        run: go test -v ./...

      - name: Install Codecov
        run: |
          wget -q -O - https://codecov.io/bash | bash -s - -Z -f coverage.txt

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          file: coverage.txt
